apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers: 
        - name: client
          image: dedalus95/jokes-fe
          ports:
            - containerPort: 4200
          env:
            - name: API_URL
              value: "/jokes-be"
